[build]
  cmd = "go test -coverprofile=tmp/cover.out ./... && gcov2lcov -infile=tmp/cover.out -outfile=tmp/lconv.info && go build -o /tmp/nawa ./cmd/nawa"
  entrypoint = "/tmp/nawa"
  include_ext = ["go"]
  exclude_dir = ["web", "webdist", "vendor"]
  delay = 500
  kill_delay = "2s"
  send_interrupt = true

[log]
  main_only = true

[misc]
    clean_on_exit = true
